<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3cmsponsor"
 *
 * Auto generated by Extension Builder 2014-05-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'T3CM Sponsor',
	'description' => 'Displays Sponsors on the page',
	'category' => 'plugin',
	'author' => 'Patrick Lobacher',
	'author_email' => 'lobacher@plus-werk.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);